.TH "UNALZ" "1" 
.SH "NAME" 
unalz \(em decompresses alzip formatted files with names ending in ".alz" 
.SH "SYNOPSIS" 
.PP 
\fBunalz\fR [\fB-utf8\fP]  [\fB-cp949\fP]  [file.[alz]]  [file(s) ...]  [target directory]  
.SH "DESCRIPTION" 
.PP 
\fBunalz\fR tool is the utility used for decompressing alzip format file. 
It mainly operates on files with names ending in '.alz'. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below.  For a complete description, see the 
\fBInfo\fP files. 
.IP "\fB-utf8\fP         " 10 
for decompressing files written in UTF-8. 
.IP "\fB-cp949\fP         " 10 
for decompressing files written in CP949 code. 
.SH "SEE ALSO" 
.PP 
unzip (1), gzip (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Yooseong Yang yooseong@debian.org.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 any later
version published by the Free Software Foundation.
 
.\" created by instant / docbook-to-man, Sun 15 Apr 2007, 19:12 
